### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by voj** [opensha/opensha#134]
Two tests are failing. It turns out that these two tests call `testModuleSerialization()` twice which opens a zip file as a `ModuleArchive` at the end of the first call and then tries to overwrite it in the second call while the first `ModuleArchive` still has the file open.

This happens on Windows.

```
> Task :opensha:test

org.opensha.sha.earthquake.faultSysSolution.FaultSystemTestSuite > org.opensha.sha.earthquake.faultSysSolution.modules.StandardFaultSysModulesTest.testInvTargetMFDs FAILED
    java.nio.file.FileSystemException at StandardFaultSysModulesTest.java:371

org.opensha.sha.earthquake.faultSysSolution.FaultSystemTestSuite > org.opensha.sha.earthquake.faultSysSolution.modules.StandardFaultSysModulesTest.testRegionsOfInterest FAILED
    java.nio.file.FileSystemException at StandardFaultSysModulesTest.java:371

3654 tests completed, 2 failed
```

**Comment by kevinmilner** [comment]
weird, I haven't been able to reproduce this, maybe a windows only issue? But either way your solution looks good (it not being closed was an oversight).

**Comment by voj** [comment]
@kevinmilner could be the OS, could be the JDK if yours has a bit more eager garbage collection.
