### ISSUE TITLE
Basic questions from a new user

### ISSUE THREAD

**Issue by zhihengw** [opensha/opensha#23]
Hi, I am new to OpenSHA and have followed the tutorial to finish some cases. Then I get a few questions that I would like to ask:
1. In the calculation type, what is the difference between probabilistic and deterministic in terms of the algorithms?
2. If I only want to work on one hazard model and change the values of model parameters in each simulation, should I choose "deterministic" and select a specific model from the "Set IMR" and "Eqk Rup Forecast" lists, then manually modify the parameter values to run each simulation?
3. Is it possible to work on a script-based model so that batch processing is applicable?

Thanks a lot!

**Comment by kevinmilner** [comment]
Hello, replies below.

> 1.In the calculation type, what is the difference between probabilistic and deterministic in terms of the algorithms?

Probabilistic is standard PSHA: the probability of exceeding an intensity measure at a site, considering all earthquakes and their probabilities as supplied by an ERF, and the ground motions expected from those earthquakes from an IMR (aka GMM aka GMPE). Deterministic gives conditional ground motion exceedance probabilities: conditioned on the occurrence of a single earthquake (either from an ERF or user defined), gives the probability of exceeding various IMs.

> 2. If I only want to work on one hazard model and change the values of model parameters in each simulation, should I choose "deterministic" and select a specific model from the "Set IMR" and "Eqk Rup Forecast" lists, then manually modify the parameter values to run each simulation?

I'm not sure I follow your question, but you might be thinking of "deterministic" in the reproducible manner, not in the "deterministic seismic hazard analysis" manner.

> 3. Is it possible to work on a script-based model so that batch processing is applicable?

Yes if you're familiar with writing java code, but there's not command line interface currently available. I agree that it would be a great tool to have, but most of our development resources have been focused on model development of late. You might try OpenQuake as well, which is command line: https://www.globalquakemodel.org/openquake

**Comment by zhihengw** [comment]
Thank you very much for your notes Kevin. Let me try a bit more.
