### ISSUE TITLE
running UCERF3 logic-tree for multiple ground motion prediction equations and sites

### ISSUE THREAD

**Issue by BabakGhods3** [opensha/opensha#35]
To Whom It May Concern

I am new to openSHA but generally familiar with the program. I want to run UCERF3 logic-tree for multiple ground motion prediction equations and sites. This can be done manually using “UCERF3 Single branch ERF”; however, considering that this logic-tree has 1440 branches, it is extremely tedious. I was wondering if there is any easier way to do this? 
Any advice you could give would be much appreciated.

Thank you very much in advance
Sincerely yours 
Babak Ghods

**Comment by kevinmilner** [comment]
Hello,

The latest nightly builds of our applications contain an "Epistemic List ERF" version of UCERF3 that automates the calculation across the full (or a subset of the) time-independent logic tree. Download one and give it a try here:

http://opensha.usc.edu/apps/opensha/nightlies/latest/

These calculations can be fairly slow, especially if gridded seismicity is required (and enabled). Make sure to also allocate plenty of memory to java when launching, certainly no less than 4 GB (and hopefully more), e.g. (for 8 GB):

java -Xmx8G -jar /path/to/file.jar

Another thing to note is that our nightly builds now require Java 11 or greater, and the next formal release will also require this.

Kevin

**Comment by BabakGhods3** [comment]
Thank you very much for your response, it works perfectly. You saved me a lot of time.
Sincerely yours
Babka Ghods

**Comment by BabakGhods3** [comment]
Just one more question is there a similar Epistemic List for UCERF2 (containing all 480 branches)?

**Comment by kevinmilner** [comment]
There is one in the same drop down box called "UCERF2 ERF Epistemic List". It predates me so I can't speak it how it works or it's completeness, I see 144 branches when I try to calculate with it.

**Comment by BabakGhods3** [comment]
Thank you very much again, you helped me a lot.
Sincerely yours
Babka Ghods
