### ISSUE TITLE
Add Mark's Simplified logA-Mw scaling relations

### ISSUE THREAD

**Issue by thingbaijam** [opensha/opensha#46]
We want to implement the simplified source scaling relations from Mark, which are as follows:
For  Strike-slip events:
Mw = logA + 3.65
Mw = logA + 4.3
For reverse and normal faulting events:
Mw = logA + 3.95
Mw = logA + 4.3
For subduction interface events:
Mw = logA + 3.6
Mw = logA + 4.1

This issue will be resolve after:
- [x] Mark's simplified logA-M scaling relations are implemented.
- [x] Generate data for testing and implement codes for testing

**Comment by kevinmilner** [comment]
Closing this issue as I think it was addressed by #48, feel free to reopen if additional work is required
