### ISSUE TITLE
Can the app calculate the risk for the region in China?

### ISSUE THREAD

**Issue by YexiangYan** [opensha/opensha#54]
Hello, excellent app! I just recently came across OpenSHA, can the app calculate the risk for the region in China? Is it possible to set it by latitude and longitude? Thanks.

**Comment by kevinmilner** [comment]
Hello, we don't currently have any source models (ERFs) implemented for China. You could code one up yourself, or use the app to calculate scenario shakemaps for your own faults.

The GEM project's OpenQuake might have China source models implemented, I suggest you look there.
