### ISSUE TITLE
UncertainArbDiscDataset missing from master branch

### ISSUE THREAD

**Issue by mbarall** [opensha/opensha#55]
@kevinmilner,

The master branch won't compile because org.opensha.commons.data.function.UncertainArbDiscDataset is missing.  Could you restore it?

Thanks.

**Comment by mbarall** [comment]
@kevinmilner 

Sorry, it's actually opensha-oaf that fails to compile because it contains references to UncertainArbDiscDataset.  Still, is it OK to restore UncertainArbDiscDataset?

**Comment by kevinmilner** [comment]
Hi @mbarall, that class was moved when #53 was merged in. I committed a change to opensha-oaf at that time to point to the new location. Pull the opensha-oaf project to get it and things should compile:

https://github.com/opensha/opensha-oaf/commit/55cfb901e6a54e43c3e82f0a0c6d848ba2e7b8dc

Let me know if you run into any issues!

**Comment by mbarall** [comment]
Hi @kevinmilner

That fixed the problem.  Thanks.
