### ISSUE TITLE
Not all .jar files obtained after compilation

### ISSUE THREAD

**Issue by ioannis-vm** [opensha/opensha#58]
Hello!
Newbie here. When I clone the repository and issue `./gradlew assemble` , I get some output that shows it's compiling and finally I get
```
BUILD SUCCESSFUL in 26s
5 actionable tasks: 5 executed
```
Then, when I `~ifind . -name '*.jar'`, I get
```
./lib/EventWebService.jar
./lib/flanagan.jar
./build/libs/opensha-dev-all.jar
./build/libs/opensha-dev.jar
./gradle/wrapper/gradle-wrapper.jar
```
I thought that `AttenuationRelationshipGUI-1.5.2.jar`, `HazardCurveGUI-1.5.2.jar`, `HazardSpectrumGUI-1.5.2.jar` etc. would be obtained in this process.
What am I missing?
Thank you!

System info:
Ubuntu 20.04 Linux 5.11.0-40-generic amd64
Gradle 4.4.1

**Comment by kevinmilner** [comment]
Hi there, welcome aboard!

The project is set up a bit differently than some other gradle projects, so you'll have to use some other commands if you want to build the applications.

If you want to build all of the applications with one command, it's `./gradlew appJars`. If you want to build a library jar with all of the compiled OpenSHA code, but no dependencies, it's `./gradlew jar`, and if you want the same but with all dependent libraries included it's `./gradlew fatJar`.

If you just want to download recent builds of the applications, you can access nightlies here: http://opensha.usc.edu/apps/opensha/nightlies/latest/

This should certainly be added to the documentation somewhere, I'll leave this issues open as a reminder to do so.

**Comment by ioannis-vm** [comment]
Thank you, that worked!
Awesome.
