### ISSUE TITLE
Uncaught exceptions in SectBySectDetailPlots leading to 'phantom' thread execution

### ISSUE THREAD

**Issue by chrisbc** [opensha/opensha#66]
When an IllegalStateException is raised by a sub-plot within the SectBySect loop, the exception is recast as a runtime error and thrown. In our NZSHM use case calling thread catch will the exception and terminate, leaving the SectBySect thread(s) to continue running .

Ideally these exceptions should be reported to stderr and the process should continue attempting to produce sub-reports.

**Comment by kevinmilner** [comment]
How about you try again after this fix (4b0cda4), does that do the trick? I think I want the full plot to fail if an exception is encountered, but to still continue on at the report level to create any other plots. What exceptions are you getting? I'd rather just fix them then skip faults that trigger some edge case.

**Comment by chrisbc** [comment]
Thanks @kevinmilner
