### ISSUE TITLE
Feature: Inversion Diagnostics  - new Regional Section

### ISSUE THREAD

**Issue by chrisbc** [opensha/opensha#73]
As opensha inversion users we want to see solution views at a regional level to support our understanding of solution results  for specific regions. 

 - [x] Add ability to defined a list of report regions (a module?)
 - [x] Solution MFD view (no targets obviously) nucl/part/cum/incr (ie similar to a named fault)

**Comment by chrisbc** [comment]
@kevinmilner we can do this or you  what-evers easiest. @voj

**Comment by kevinmilner** [comment]
@chrisbc @voj  Probably simplest for me to do it, and we'll benefit as well, so I'll work on it now. Shouldn't take long!

**Comment by kevinmilner** [comment]
OK should now all be there. See `org.opensha.sha.earthquake.faultSysSolution.modules.RegionsOfInterest`, I'll let you close this issue after giving it a test drive
