### ISSUE TITLE
Site Data

### ISSUE THREAD

**Issue by lstrahm** [opensha/opensha#90]
Can't use Site Data.  We've tried this on a Mac and 2 PC's.  It opened once on each machine and we got the "oops1" message.  Then it wouldn't open at all.

Thanks!
Larry Strahm

**Comment by kevinmilner** [comment]
Hello, a power issue in our server room has caused our server to be down. Our IT staff won't be able to fix it until Monday, you can watch the ["Server Status Test" icon here](https://github.com/opensha/opensha#opensha), when it turns green then the server is back up.

**Comment by lstrahm** [comment]
Thanks!!!!
